#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'

begin
  if RUBY_VERSION >= '2.0'
    require 'byebug'
  elsif RUBY_VERSION >= '1.9'
    require 'debugger'
  else
    require 'ruby-debug'
  end
rescue LoadError
end

require 'mail'

require 'irb'
require 'irb/completion'
IRB.start
